#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      env CFLAGS=-O2 pkg ensure www/squid www/squid3
      ;;
    *)
      pkg ensure www/squid www/squid3
      ;;
  esac
}

main "$@"
