#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_example="0.0.1"
  jq -n --arg example "$ver_example" '{example: $example}'
}

version "$@"
